apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: default
  labels:
    app: django-app
spec:
  #revisionHistoryLimit: 10  # removes old replicasets for deployment rollbacks
  #strategy:
  #  rollingUpdate:
  #    maxUnavailable: 0  # Avoid Terminating and ContainerCreating at the same time
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: app
          image: 448389607377.dkr.ecr.us-west-2.amazonaws.com/djangoapp:0.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            periodSeconds: 60

