apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pg-us-west-2
  region: us-west-2

nodeGroups:
  - name: spot
    labels:  
      project: pgBufferContentLWLocks
      lifecycle: Ec2Spot
      aws.amazon.com/spot: "true"
    maxSize: 100
    minSize: 10
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    instancesDistribution:
      instanceTypes: ["m5dn.4xlarge","c5a.4xlarge","r5b.4xlarge","r4.4xlarge","r5dn.4xlarge","r5.4xlarge","r5ad.4xlarge","r5n.4xlarge","c5.4xlarge","c5d.4xlarge","m5.4xlarge","m5a.4xlarge","m5n.4xlarge","c4.4xlarge","c3.4xlarge"]
      onDemandPercentageAboveBaseCapacity: 0
      onDemandBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
    taints:
      spotInstance: "true:PreferNoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/project: pgBufferContentLWLocks
      k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
  - name: ondemand
    labels:  
      project: pgBufferContentLWLocks
      instance.size: 4xlarge
      lifecycle: Ec2OnDemand
      aws.amazon.com/spot: "false"
    maxSize: 100
    minSize: 50
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    instancesDistribution:
      instanceTypes: ["m5dn.4xlarge","c5a.4xlarge","r5b.4xlarge","r4.4xlarge","r5dn.4xlarge","r5.4xlarge","r5ad.4xlarge","r5n.4xlarge","c5.4xlarge","c5d.4xlarge","m5.4xlarge","m5a.4xlarge","m5n.4xlarge","c4.4xlarge","c3.4xlarge"]
      onDemandPercentageAboveBaseCapacity: 100
      onDemandBaseCapacity: 100
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2OnDemand
      k8s.io/cluster-autoscaler/node-template/label/project: pgBufferContentLWLocks
      k8s.io/cluster-autoscaler/node-template/label/instance.size: 4xlarge
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "false"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
