create user postgres1 with password 'Admin1234!';
grant postgres1 to postgres;
create user postgres2 with password 'Admin1234!';
grant postgres2 to postgres;
create user postgres3 with password 'Admin1234!';
grant postgres3 to postgres;
create user postgres4 with password 'Admin1234!';
grant postgres4 to postgres;
create user postgres5 with password 'Admin1234!';
grant postgres5 to postgres;
create user postgres6 with password 'Admin1234!';
grant postgres6 to postgres;
create user postgres7 with password 'Admin1234!';
grant postgres7 to postgres;
create user postgres8 with password 'Admin1234!';
grant postgres8 to postgres;
create user postgres9 with password 'Admin1234!';
grant postgres9 to postgres;
create user postgres10 with password 'Admin1234!';
grant postgres10 to postgres;
create user postgres11 with password 'Admin1234!';
grant postgres11 to postgres;
create user postgres12 with password 'Admin1234!';
grant postgres12 to postgres;
create user postgres13 with password 'Admin1234!';
grant postgres13 to postgres;
create user postgres14 with password 'Admin1234!';
grant postgres14 to postgres;
