apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appupdatepg
  name: appupdatepg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appupdatepg
  template:
    metadata:
      labels:
        app: appupdatepg
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: default
      containers:
        - name: appupdatepg
          envFrom:
            - secretRef:
                name: pg-creds
          env:
            - name: QUEUE_URL
              value: "https://sqs.us-west-2.amazonaws.com/498254202105/pg"
            - name: NUM_OF_UPDATE_THREADS
              value: "60"
          image: 498254202105.dkr.ecr.us-west-2.amazonaws.com/simu-app-load:arm0.5
          imagePullPolicy: Always
          command: ["/app-update.sh"]
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
      hostNetwork: true
