apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appinsert-logistics
  name: appinsert-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appinsert-logistics
  template:
    metadata:
      labels:
        app: appinsert-logistics
    spec:
      #nodeSelector:
      #  lifecycle: Ec2Spot
      containers:
        - name: appinsert-logistics
          envFrom:
            - secretRef:
                name: logistics-creds
          env:
            - name: QUEUE_URL
              value: "https://sqs.us-west-2.amazonaws.com/448389607377/logistics"
            - name: NUM_OF_SINGLE_INSERTS
              value: "50"
            - name: DBHOST
              #value: "logistics.czk5ni6ofaxj.us-west-2.rds.amazonaws.com"
              value: "a6f17cd47c99c40a292a9649c37de242-3f039135050408d8.elb.us-west-2.amazonaws.com"
          image: 448389607377.dkr.ecr.us-west-2.amazonaws.com/simu-app-load:0.2
          imagePullPolicy: Always
          command: ["/app-insert.sh"]
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
      hostNetwork: true
