apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-load-db-10-14-postgres1
  name: app-load-db-10-14-postgres1
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: app-load-db-10-14-postgres1
  template:
    metadata:
      labels:
        app: app-load-db-10-14-postgres1
    spec:
      #nodeSelector:
      #  lifecycle: Ec2Spot
      containers:
        - name: app-load-db-10-14-postgres1
          envFrom:
            - secretRef:
                name: db-10-14-seq-creds
          env:
            - name: UPDATE_ORDER_RANGE
              value: "200"
            - name: MIN_SLEEP_BETWEEN_UPDATES
              value: "100"
            - name: MAX_SLEEP_BETWEEN_UPDATES
              value: "200"
            - name: QUEUE_URL
              value: "https://sqs.us-west-2.amazonaws.com/448389607377/delivery-id-db-10-14-seq"
            - name: NUM_OF_SINGLE_INSERTS
              value: "70"
            - name: DBHOST
              value: "ab06f341e1f474677ad49fcd3eadfbed-da6b60458fed2c70.elb.us-west-2.amazonaws.com"
          image: 448389607377.dkr.ecr.us-west-2.amazonaws.com/simu-app-load:0.2
          imagePullPolicy: Always
          command: ["/app-update.sh"]
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
      hostNetwork: true
