apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appupdate
  name: appupdate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appupdate
  template:
    metadata:
      labels:
        app: appupdate
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: default
      containers:
        - name: appupdate
          envFrom:
            - secretRef:
                name: db-creds
          env:
            - name: DBHOST
              value: "pg.cuzis87cjlbq.us-west-2.rds.amazonaws.com"
            - name: QUEUE_URL
              value: "https://sqs.us-west-2.amazonaws.com/498254202105/db"
            - name: NUM_OF_UPDATE_THREADS
              value: "60"
          image: 498254202105.dkr.ecr.us-west-2.amazonaws.com/simu-app-load:arm0.5
          imagePullPolicy: Always
          command: ["/app-update.sh"]
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
      hostNetwork: true
