apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::448389607377:role/eksctl-dd-us-west-2-nodegroup-spo-NodeInstanceRole-881Q4MLLMDP0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::448389607377:role/eksctl-dd-us-west-2-nodegroup-ond-NodeInstanceRole-Y69ZAELDPIYG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:sts::448389607377:assumed-role/AWSReservedSSO_PowerUserAccess_2474040295748ec7/wuang
      username: wuang
      groups:
        - system:masters
