apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dd-x86-us-west-2
  region: us-west-2

managedNodeGroups:
  - name: x86managed-ng-1
    labels:  
      project: doordash
      nglb: x86managed-ng-1
    instanceTypes: ["m5dn.xlarge","c5a.xlarge","r5b.xlarge","r4.xlarge","r5dn.xlarge","r5.xlarge","r5ad.xlarge","r5n.xlarge","c5.xlarge","c5d.xlarge","m5.xlarge","m5a.xlarge","m5n.xlarge","c4.xlarge","c3.xlarge"]
    maxSize: 100
    minSize: 1
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    tags:
      project: doordash
      ngt: x86managed-ng-1
    iam:
      withAddonPolicies:
        cloudWatch: true
        albIngress: true
        externalDNS: true
        certManager: true
