apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: adc-us-west-2
  region: us-west-2

nodeGroups:
  - name: spot
    labels:  
      project: adcolony
      lifecycle: Ec2Spot
      instance.size: xlarge
      aws.amazon.com/spot: "true"
    maxSize: 10
    minSize: 1
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    instancesDistribution:
      instanceTypes: ["m5dn.xlarge","c5a.xlarge","r5b.xlarge","r4.xlarge","r5dn.xlarge","r5.xlarge","r5ad.xlarge","r5n.xlarge","c5.xlarge","c5d.xlarge","m5.xlarge","m5a.xlarge","m5n.xlarge","c4.xlarge","c3.xlarge"]
      onDemandPercentageAboveBaseCapacity: 0
      onDemandBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
    taints:
      spotInstance: "true:PreferNoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/project: adcolony
      k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
