---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-handler
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-handler
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-handler
  namespace: default
subjects:
- kind: ServiceAccount
  name: node-handler
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-handler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-handler
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-handler
  template:
    metadata:
      labels:
        app: node-handler
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: default
      serviceAccountName: node-handler
      containers:
      - name: node-handler
        image: 498254202105.dkr.ecr.us-west-2.amazonaws.com/simu-app-load:arm0.7
        imagePullPolicy: Always
        command: ["/ds-start.sh"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
