apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-db-9-6
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  namespace: default
  labels:
    app: pgbouncer-db-9-6
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  type: LoadBalancer
  selector:
    app: pgbouncer-db-9-6
