apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-db
  namespace: default
  labels:
    app: pgbouncer-db
spec:
  selector:
    matchLabels:
      app: pgbouncer-db
  template:
    metadata:
      labels:
        app: pgbouncer-db
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:1.9.0
          #imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
               name: db-creds
          env:
            - name: MAX_CLIENT_CONN
              value: "10000"
            - name: MAX_CONNECTIONS
              value: "200"
            - name: POOL_MODE
              value: transaction
            - name: SERVER_RESET_QUERY
              value: DISCARD ALL
          livenessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                # Allow existing queries clients to complete within 120 seconds
                command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['all']
