apiVersion: batch/v1
kind: CronJob
metadata:
  name: vacuum-db
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vacuum-db
            envFrom:
              - secretRef:
                  name: db-creds 
            env:
              - name: DBHOST
                value: "eks-dd-arm-us-west-2.endpoint.proxy-czk5ni6ofaxj.us-west-2.rds.amazonaws.com"
            image: 448389607377.dkr.ecr.us-west-2.amazonaws.com/simu-app-load:arm0.5
            imagePullPolicy: Always
            command: ["/vacuum.sh"]
          restartPolicy: OnFailure 
