apiVersion: batch/v1
kind: CronJob
metadata:
  name: vacuum-pgp
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vacuum-pgp
            envFrom:
              - secretRef:
                  name: pgp-creds 
            env:
            image: 498254202105.dkr.ecr.us-west-2.amazonaws.com/simu-app-load:arm0.7
            imagePullPolicy: Always
            command: ["/vacuum.sh"]
          restartPolicy: OnFailure 
