apiVersion: v1
data:
  PGB_ADMIN_PASSWORDS: QWRtaW4xMjM0IQ==
  PGB_ADMIN_USERS: cG9zdGdyZXM=
  PGB_DATABASES: cG9zdGdyZXMgPSBob3N0PXN0ay5jZW5wMXZ1cjk1NzQudXMtd2VzdC0yLnJlZHNoaWZ0LmFtYXpvbmF3cy5jb20gZGJuYW1lPXBvc3RncmVz
kind: Secret
metadata:
  creationTimestamp: null
  name: pgbouncer
  namespace: default
