---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adaptivepgbouncer
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  - extensions
  - apps
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - pods
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adaptivepgbouncer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adaptivepgbouncer
  namespace: default
subjects:
- kind: ServiceAccount
  name: adaptivepgbouncer
  namespace: default
roleRef:
  kind: ClusterRole
  name: adaptivepgbouncer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: default
  labels:
    app: pgbouncer
spec:
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      serviceAccountName: adaptivepgbouncer
      containers:
        - name: pgbouncer
          image: 498254202105.dkr.ecr.us-west-2.amazonaws.com/pgbouncer:1.12.0-3-aarch64
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 1024m
              memory: 1024Mi
              ephemeral-storage: 512Mi
          envFrom:
            - secretRef:
               name: pgbouncer
          env:
            - name: default_pool_size
              value: "20"
            - name: PGB_LISTEN_PORT
              value: "5432"
            - name: PGB_LISTEN_ADDR
              value: "0.0.0.0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
