apiVersion: v1
data:
  PGB_ADMIN_PASSWORDS: QWRtaW4xMjM0IQ==
  PGB_ADMIN_USERS: cGdib3VuY2Vy
  PGB_DATABASES: cG9zdGdyZXMgPSBob3N0PXBnLmN1emlzODdjamxicS51cy13ZXN0LTIucmRzLmFtYXpvbmF3cy5jb20gZGJuYW1lPXBvc3RncmVz
kind: Secret
metadata:
  creationTimestamp: null
  name: pgbouncer
  namespace: default
