# Generated by Django 3.2.7 on 2021-09-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
