# Generated by Django 3.2.7 on 2021-09-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_delivery_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
