# Generated by Django 3.2.8 on 2021-10-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
